name: Ruby

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-16.04 ]
        ruby: [ '2.6.3' ]

    steps:
    - uses: zhulik/redis-action@v1.0.0
      with:
        redis version: '4'

    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '12'

    - uses: actions/checkout@master
    - name: Setup ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        architecture: 'x64'

    - name: Updates apt-get
      run: apt-get update
  
    - name: Setup packages
      uses: mstksg/get-package@v1
      with:
        apt-get: gifsicle jpegoptim optipng jhead

    - name: Before install
      run: 
        node --version
        gem install bundler -v 1.17.3

    - name: Run
      run: bundle exec rake db:create && LOAD_PLUGINS=1 bundle exec rake db:migrate
