name: Ruby

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      DISCOURSE_HOSTNAME: www.example.com
      RUBY_GLOBAL_METHOD_CACHE_SIZE: 131072
      BUILD_TYPE: ${{ matrix.build_types }}

    strategy:
      fail-fast: true

      matrix:
        build_types: [ 'BACKEND', 'FRONTEND', 'LINTING']
        os: [ ubuntu-16.04 ]
        ruby: [ '2.6.3' ]

    services:
      redis:
        image: redis
        ports:
          - 6379/6379
      postgres:
        image: postgres:12
        ports: ["5432:5432"]

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Setup ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        architecture: 'x64'

    - name: Updates apt-get
      run: sudo apt-get update
  
    - name: Setup packages
      uses: mstksg/get-package@v1
      with:
        apt-get: libpq-dev gifsicle jpegoptim optipng jhead

    - name: Build App
      env:
        RAILS_ENV: test
      run: |
        node --version
        gem install bundler -v 1.17.3 --no-doc
        bundle install --jobs 4 --retry 3
        bin/rails db:setup

    - name: Run
      run: bundle exec rake db:create && LOAD_PLUGINS=1 bundle exec rake db:migrate
