name: Discourse

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      DISCOURSE_HOSTNAME: www.example.com
      RUBY_GLOBAL_METHOD_CACHE_SIZE: 131072
      BUILD_TYPE: ${{ matrix.build_types }}

    strategy:
      fail-fast: true

      matrix:
        build_types: [ 'BACKEND', 'FRONTEND', 'LINTING']
        os: [ ubuntu-latest ]
        ruby: [ '2.6.3' ]
        postgres: [ '12' ]
        redis: [ '4.x' ]

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: discourse
          POSTGRES_PASSWORD: discourse
          POSTGRES_DB: discourse_test
        ports: 
          - 5432:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ matrix.redis }}

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'

      - name: Updates apt-get
        run: sudo apt-get update

      - name: Setup packages
        uses: mstksg/get-package@v1
        with:
          apt-get: postgresql-client libpq-dev gifsicle jpegoptim optipng jhead

      - name: Build App
        env:
          RAILS_ENV: test
          DB_USERNAME: discourse
          DB_PASSWORD: discourse
          DB_PORT: ${{ job.services.postgres.ports['5432'] }}
          DB_HOST: localhost
          RAILS_DB: discourse_test
          DATABASE_URL: postgresql://discourse:discourse@localhost/discourse_test

        run: |
          node --version
          gem install bundler -v 1.17.3 --no-doc
          bundle install --without development --deployment --jobs 4 --retry 3
      #     bin/rails db:setup

      # - name: Run
      #   run: bundle exec rake db:create && LOAD_PLUGINS=1 bundle exec rake db:migrate
