name: Discourse

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      DISCOURSE_HOSTNAME: www.example.com
      RUBY_GLOBAL_METHOD_CACHE_SIZE: 131072
      BUILD_TYPE: ${{ matrix.build_types }}

    steps:
      - name: Run Tests
        uses: docker://discourse/discourse-test:release
